export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "学历码",
      "prop": "xlm",
      "span": 12
    },	  {
      "type": "input",
      "label": "入学时间",
      "prop": "rxsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "学习形式码",
      "prop": "xxxsm",
      "span": 12
    },	  {
      "type": "input",
      "label": "学制",
      "prop": "xz",
      "span": 12
    },	  {
      "type": "input",
      "label": "毕业时间",
      "prop": "bysj",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
