export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "护照证件种类代码",
      "prop": "hzzjzldm",
      "span": 12
    },	  {
      "type": "input",
      "label": "护照号/通行证号",
      "prop": "hzhtxzh",
      "span": 12
    },	  {
      "type": "input",
      "label": "签发地点",
      "prop": "qfdd",
      "span": 12
    },	  {
      "type": "input",
      "label": "签发日期",
      "prop": "qfrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "签发机关",
      "prop": "qfjg",
      "span": 12
    },	  {
      "type": "input",
      "label": "终止日期",
      "prop": "zzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
