export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "id",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "外聘教师id",
      "prop": "wpjsId",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书类别",
      "prop": "zslb",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书等级",
      "prop": "zsdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书名称",
      "prop": "zsmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "发证单位",
      "prop": "fzdw",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书编号",
      "prop": "zsbh",
      "span": 12
    },	  {
      "type": "input",
      "label": "获取日期",
      "prop": "hqrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "delFlag",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
