export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "学校主管部门码",
      "prop": "xxzgbmm",
      "span": 12
    },	  {
      "type": "input",
      "label": "职务名称",
      "prop": "zwmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "任职方式码",
      "prop": "rzfsm",
      "span": 12
    },	  {
      "type": "input",
      "label": "任免职文号",
      "prop": "rmzwh",
      "span": 12
    },	  {
      "type": "input",
      "label": "职务级别码",
      "prop": "zwjbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "任职日期",
      "prop": "rzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
