export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "工人技术等级名称",
      "prop": "grjsdjmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "工人技术职务名称",
      "prop": "grjszwmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "取得技术职务时间",
      "prop": "qdjszwsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "批准技术职务单位名称",
      "prop": "pzjszwdwmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书编号",
      "prop": "zsbh",
      "span": 12
    },	  {
      "type": "input",
      "label": "工人工种码",
      "prop": "grgzm",
      "span": 12
    },	  {
      "type": "input",
      "label": "上传电子证件",
      "prop": "szdczj",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
