export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "教师资格证种类码",
      "prop": "jszgzzlm",
      "span": 12
    },	  {
      "type": "input",
      "label": "教师资格证号码",
      "prop": "jszgzhm",
      "span": 12
    },	  {
      "type": "input",
      "label": "任教学科码",
      "prop": "xjxkm",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更行时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
