export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "部门（处室）",
      "prop": "bm",
      "span": 12
    },	  {
      "type": "input",
      "label": "人员类别",
      "prop": "rylb",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位类别",
      "prop": "gwlbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位等级",
      "prop": "gwdjm",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位聘任年月",
      "prop": "gwprny",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位聘任年限",
      "prop": "gwprnx",
      "span": 12
    },	  {
      "type": "input",
      "label": "参加工作时间",
      "prop": "cjgzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "实际工作年限",
      "prop": "cjgzny",
      "span": 12
    },	  {
      "type": "input",
      "label": "进入本单位工作时间",
      "prop": "jrbdwgzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "校内职务",
      "prop": "xnzw",
      "span": 12
    },	  {
      "type": "input",
      "label": "任现职务时间",
      "prop": "rxzwsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "所属教研组",
      "prop": "ssjyz",
      "span": 12
    },	  {
      "type": "input",
      "label": "教龄",
      "prop": "jl",
      "span": 12
    },	  {
      "type": "input",
      "label": "人员录聘来源",
      "prop": "rylply",
      "span": 12
    },	  {
      "type": "input",
      "label": "用工形式",
      "prop": "ygxs",
      "span": 12
    },	  {
      "type": "input",
      "label": "试用期限",
      "prop": "syqx",
      "span": 12
    },	  {
      "type": "input",
      "label": "减员时间",
      "prop": "jysj",
      "span": 12
    },	  {
      "type": "input",
      "label": "减员材料上传",
      "prop": "jyclsc",
      "span": 12
    },	  {
      "type": "input",
      "label": "专业技术职务",
      "prop": "xrzyjszw",
      "span": 12
    },	  {
      "type": "input",
      "label": "专业技术等级",
      "prop": "zyjsdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否为内设机构领导",
      "prop": "sfwnsjgld",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否留学回国",
      "prop": "sflxhg",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否残疾人",
      "prop": "sfcjr",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否为应届毕业生",
      "prop": "sfyjbys",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
