export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "社会兼职起始日期",
      "prop": "shjzqsrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "社会兼职终止日期",
      "prop": "shjzzzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "任职组织",
      "prop": "rzzz",
      "span": 12
    },	  {
      "type": "input",
      "label": "组织类型",
      "prop": "zzlx",
      "span": 12
    },	  {
      "type": "input",
      "label": "兼职职务",
      "prop": "jzzw",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否取酬",
      "prop": "sfqc",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
