export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "处分类别",
      "prop": "cflb",
      "span": 12
    },	  {
      "type": "input",
      "label": "惩处名称",
      "prop": "ccmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "惩处日期",
      "prop": "ccrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "惩处原因",
      "prop": "ccyy",
      "span": 12
    },	  {
      "type": "input",
      "label": "惩处撤销日期",
      "prop": "cccxrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "监察机关直接给予",
      "prop": "jcjgzjjy",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
