export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业工种",
      "prop": "zygz",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业等级",
      "prop": "zydj",
      "span": 12
    },	  {
      "type": "input",
      "label": "颁证机构",
      "prop": "bzjg",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业资格证书编号",
      "prop": "zyzgzsbh",
      "span": 12
    },	  {
      "type": "input",
      "label": "证书颁发日期",
      "prop": "zsbfrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
