export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "师训帐号",
      "prop": "sxzh",
      "span": 12
    },	  {
      "type": "input",
      "label": "双师型教师认定",
      "prop": "ssxjsrd",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否教研组长",
      "prop": "sfjyzz",
      "span": 12
    },	  {
      "type": "input",
      "label": "教研组长备注",
      "prop": "jyzzbz",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否名师工作室主持人",
      "prop": "sfmsgzszcr",
      "span": 12
    },	  {
      "type": "input",
      "label": "名师工作室主持人级别",
      "prop": "msgzszcrjb",
      "span": 12
    },	  {
      "type": "input",
      "label": "名师工作室主持人备注",
      "prop": "msgzszcrbz",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否学科带头人",
      "prop": "sfxkdtr",
      "span": 12
    },	  {
      "type": "input",
      "label": "学科带头人备注",
      "prop": "xkdtrbz",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否骨干教师",
      "prop": "sfggjs",
      "span": 12
    },	  {
      "type": "input",
      "label": "骨干教师备注",
      "prop": "ggjsbz",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否学术委员会成员",
      "prop": "sfxswyhcy",
      "span": 12
    },	  {
      "type": "input",
      "label": "学术委员会成员备注",
      "prop": "xswyhcybz",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否督导组成员",
      "prop": "sfddzcy",
      "span": 12
    },	  {
      "type": "input",
      "label": "督导组成员备注",
      "prop": "ddzcybz",
      "span": 12
    },	  {
      "type": "input",
      "label": "教师资格证上传",
      "prop": "jszgzsc",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
