export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "中国建设银行卡号",
      "prop": "zgjsyhkh",
      "span": 12
    },	  {
      "type": "input",
      "label": "中国工商银行卡号",
      "prop": "zggsyhkh",
      "span": 12
    },	  {
      "type": "input",
      "label": "中国银行卡号",
      "prop": "zgyhkh",
      "span": 12
    },	  {
      "type": "input",
      "label": "公积金账号",
      "prop": "gjjzh",
      "span": 12
    },	  {
      "type": "input",
      "label": "补充公积金账号",
      "prop": "bcgjjzh",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
