export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "专业技术资格名称",
      "prop": "zyjszgmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "取得资格途径码",
      "prop": "qdzgtjm",
      "span": 12
    },	  {
      "type": "input",
      "label": "取得资格时间",
      "prop": "hdzgsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "任职资格名称码",
      "prop": "rzzgmcm",
      "span": 12
    },	  {
      "type": "input",
      "label": "首次聘任时间",
      "prop": "scprsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任起始日期",
      "prop": "prqsrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任终止日期",
      "prop": "przzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任情况码",
      "prop": "prqkm",
      "span": 12
    },	  {
      "type": "input",
      "label": "上传电子证件",
      "prop": "scdzzj",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
