export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "id",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "工号",
      "prop": "gh",
      "span": 12
    },	  {
      "type": "input",
      "label": "姓名",
      "prop": "xm",
      "span": 12
    },	  {
      "type": "input",
      "label": "英文姓名",
      "prop": "ywxm",
      "span": 12
    },	  {
      "type": "input",
      "label": "姓名拼音",
      "prop": "xmpy",
      "span": 12
    },	  {
      "type": "input",
      "label": "曾用名",
      "prop": "cym",
      "span": 12
    },	  {
      "type": "input",
      "label": "身份证件类型码",
      "prop": "sfzjlxm",
      "span": 12
    },	  {
      "type": "input",
      "label": "身份证号",
      "prop": "sfzjh",
      "span": 12
    },	  {
      "type": "input",
      "label": "身份证正面",
      "prop": "sfzFrontImg",
      "span": 12
    },	  {
      "type": "input",
      "label": "身份证反面",
      "prop": "sfzBackImg",
      "span": 12
    },	  {
      "type": "input",
      "label": "出生日期",
      "prop": "csrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "出生地",
      "prop": "csd",
      "span": 12
    },	  {
      "type": "input",
      "label": "性别码",
      "prop": "xbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "民族码",
      "prop": "mzm",
      "span": 12
    },	  {
      "type": "input",
      "label": "政治面貌码",
      "prop": "zzmmm",
      "span": 12
    },	  {
      "type": "input",
      "label": "健康状况码",
      "prop": "jkzkm",
      "span": 12
    },	  {
      "type": "input",
      "label": "婚姻状况码",
      "prop": "hyzkm",
      "span": 12
    },	  {
      "type": "input",
      "label": "港澳台侨外码",
      "prop": "gatqwm",
      "span": 12
    },	  {
      "type": "input",
      "label": "国籍/地区码",
      "prop": "gjdqm",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否落户",
      "prop": "sflh",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否兼职教师",
      "prop": "sfjzjs",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否双师型教师",
      "prop": "sfssxjs",
      "span": 12
    },	  {
      "type": "input",
      "label": "籍贯",
      "prop": "jg",
      "span": 12
    },	  {
      "type": "input",
      "label": "联系电话",
      "prop": "lxdh",
      "span": 12
    },	  {
      "type": "input",
      "label": "电子邮箱",
      "prop": "dzyx",
      "span": 12
    },	  {
      "type": "input",
      "label": "家庭住址",
      "prop": "jtzz",
      "span": 12
    },	  {
      "type": "input",
      "label": "家庭联系人",
      "prop": "jtlxr",
      "span": 12
    },	  {
      "type": "input",
      "label": "户口详细地址",
      "prop": "hkxxdz",
      "span": 12
    },	  {
      "type": "input",
      "label": "户籍类别",
      "prop": "hjlb",
      "span": 12
    },	  {
      "type": "input",
      "label": "所获学位码",
      "prop": "shxwm",
      "span": 12
    },	  {
      "type": "input",
      "label": "所学专业名称",
      "prop": "sxzymc",
      "span": 12
    },	  {
      "type": "input",
      "label": "毕业院校",
      "prop": "byyx",
      "span": 12
    },	  {
      "type": "input",
      "label": "学历上传",
      "prop": "xlsc",
      "span": 12
    },	  {
      "type": "input",
      "label": "当前状态码",
      "prop": "dqztk",
      "span": 12
    },	  {
      "type": "input",
      "label": "合同类型",
      "prop": "htlx",
      "span": 12
    },	  {
      "type": "input",
      "label": "居住证起始时间",
      "prop": "jjzqssj",
      "span": 12
    },	  {
      "type": "input",
      "label": "居住证截止时间",
      "prop": "jjzjzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "教师职称",
      "prop": "jszc",
      "span": 12
    },	  {
      "type": "input",
      "label": "银行卡号",
      "prop": "yhkh",
      "span": 12
    },	  {
      "type": "input",
      "label": "所属教研组",
      "prop": "ssjyz",
      "span": 12
    },	  {
      "type": "input",
      "label": "入党日期",
      "prop": "rdrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "bz",
      "span": 12
    },	  {
      "type": "input",
      "label": "delFlag",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
