export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "起始时间",
      "prop": "qssj",
      "span": 12
    },	  {
      "type": "input",
      "label": "终止时间",
      "prop": "zzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "所在单位",
      "prop": "szdw",
      "span": 12
    },	  {
      "type": "input",
      "label": "职务",
      "prop": "zw",
      "span": 12
    },	  {
      "type": "input",
      "label": "单位所在省份",
      "prop": "dwszsf",
      "span": 12
    },	  {
      "type": "input",
      "label": "上传电子证明",
      "prop": "scdzzm",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
