export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "部门",
      "prop": "deptId",
      "span": 12
    },	  {
      "type": "input",
      "label": "工号",
      "prop": "gh",
      "span": 12
    },	  {
      "type": "input",
      "label": "姓名",
      "prop": "xm",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任名称",
      "prop": "engageName",
      "span": 12
    },	  {
      "type": "input",
      "label": "专家级别",
      "prop": "expertLevel",
      "span": 12
    },	  {
      "type": "input",
      "label": "待遇",
      "prop": "salary",
      "span": 12
    },	  {
      "type": "input",
      "label": "原因",
      "prop": "reason",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任开始时间",
      "prop": "sarteDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任结束时间",
      "prop": "endDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "memo",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
