export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "政治面貌码",
      "prop": "zzmmm",
      "span": 12
    },	  {
      "type": "input",
      "label": "参加日期",
      "prop": "cjrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "介绍人",
      "prop": "jsr",
      "span": 12
    },	  {
      "type": "input",
      "label": "转正日期",
      "prop": "zzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
