export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "获奖类别码",
      "prop": "hjlbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "奖励名称",
      "prop": "jlmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "获奖日期",
      "prop": "hjrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "颁奖单位",
      "prop": "bjdw",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
