export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "id",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "部门id",
      "prop": "orgId",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "工号",
      "prop": "gh",
      "span": 12
    },	  {
      "type": "input",
      "label": "姓名",
      "prop": "xm",
      "span": 12
    },	  {
      "type": "input",
      "label": "薪资",
      "prop": "xz",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位名称",
      "prop": "gwmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "开始日期",
      "prop": "startDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "结束日期",
      "prop": "endDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "bz",
      "span": 12
    },	  {
      "type": "input",
      "label": "delFlag",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
