export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "荣誉奖励级别",
      "prop": "jljbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "奖励类别",
      "prop": "jllbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "奖励名称",
      "prop": "jlmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "荣誉和奖励原因",
      "prop": "jlyy",
      "span": 12
    },	  {
      "type": "input",
      "label": "奖励时间",
      "prop": "jlsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "奖励单位",
      "prop": "jldw",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "bz",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
