export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "年度",
      "prop": "nd",
      "span": 12
    },	  {
      "type": "input",
      "label": "考核分数",
      "prop": "khfs",
      "span": 12
    },	  {
      "type": "input",
      "label": "考核等级",
      "prop": "khdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "同级人员人数",
      "prop": "tjryrs",
      "span": 12
    },	  {
      "type": "input",
      "label": "同级人员中名次",
      "prop": "tjryzmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "全校专业技术人员数",
      "prop": "qxzyjsrys",
      "span": 12
    },	  {
      "type": "input",
      "label": "全校专业技术人员名次",
      "prop": "qxzyjsrymc",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "bz",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
