export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "id",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "组织机构id",
      "prop": "orgId",
      "span": 12
    },	  {
      "type": "input",
      "label": "工号",
      "prop": "gh",
      "span": 12
    },	  {
      "type": "input",
      "label": "姓名",
      "prop": "xm",
      "span": 12
    },	  {
      "type": "input",
      "label": "性别",
      "prop": "xbm",
      "span": 12
    },	  {
      "type": "input",
      "label": "民族",
      "prop": "mzm",
      "span": 12
    },	  {
      "type": "input",
      "label": "出生日期",
      "prop": "csrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "身份证号",
      "prop": "sfzjh",
      "span": 12
    },	  {
      "type": "input",
      "label": "性质",
      "prop": "xz",
      "span": 12
    },	  {
      "type": "input",
      "label": "家庭地址",
      "prop": "jtdz",
      "span": 12
    },	  {
      "type": "input",
      "label": "联系电话",
      "prop": "lxdh",
      "span": 12
    },	  {
      "type": "input",
      "label": "户口",
      "prop": "hk",
      "span": 12
    },	  {
      "type": "input",
      "label": "四金缴纳",
      "prop": "sjjn",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否已参加综合保险",
      "prop": "sfycjzhbx",
      "span": 12
    },	  {
      "type": "input",
      "label": "学历",
      "prop": "xl",
      "span": 12
    },	  {
      "type": "input",
      "label": "学位",
      "prop": "xw",
      "span": 12
    },	  {
      "type": "input",
      "label": "参加工作(年月)",
      "prop": "cjgzrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "教师资格证",
      "prop": "jszgz",
      "span": 12
    },	  {
      "type": "input",
      "label": "双师型教师",
      "prop": "xsxjs",
      "span": 12
    },	  {
      "type": "input",
      "label": "所学专业名称",
      "prop": "sxzymc",
      "span": 12
    },	  {
      "type": "input",
      "label": "职称名称",
      "prop": "zcmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "职称等级",
      "prop": "zcdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "发证单位",
      "prop": "fzdw",
      "span": 12
    },	  {
      "type": "input",
      "label": "获取日期",
      "prop": "hqrq",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业资格证书类别",
      "prop": "zyzgzslb",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业资格证书等级",
      "prop": "zyzgzsdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "职业资格证书相关详情",
      "prop": "zyzgzsxq",
      "span": 12
    },	  {
      "type": "input",
      "label": "当前专职工作背景",
      "prop": "dqzzgzbj",
      "span": 12
    },	  {
      "type": "input",
      "label": "delFlag",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
