export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位绩点",
      "prop": "gwjd",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位等级",
      "prop": "gwdjm",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位工资",
      "prop": "gwgz",
      "span": 12
    },	  {
      "type": "input",
      "label": "薪级等级",
      "prop": "xjdj",
      "span": 12
    },	  {
      "type": "input",
      "label": "薪级工资",
      "prop": "xjgz",
      "span": 12
    },	  {
      "type": "input",
      "label": "薪级等级附件",
      "prop": "xjdjfj",
      "span": 12
    },	  {
      "type": "input",
      "label": "上下班交通费",
      "prop": "sxbjtf",
      "span": 12
    },	  {
      "type": "input",
      "label": "粮油补贴",
      "prop": "lybt",
      "span": 12
    },	  {
      "type": "input",
      "label": "教贴",
      "prop": "jt",
      "span": 12
    },	  {
      "type": "input",
      "label": "岗位津贴",
      "prop": "gwjt",
      "span": 12
    },	  {
      "type": "input",
      "label": "技术津贴",
      "prop": "jsjt",
      "span": 12
    },	  {
      "type": "input",
      "label": "工会费",
      "prop": "ghf",
      "span": 12
    },	  {
      "type": "input",
      "label": "饭贴",
      "prop": "ft",
      "span": 12
    },	  {
      "type": "input",
      "label": "工作年限",
      "prop": "gznx",
      "span": 12
    },	  {
      "type": "input",
      "label": "聘任岗位",
      "prop": "prgw",
      "span": 12
    },	  {
      "type": "input",
      "label": "任现职时间",
      "prop": "xrzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
