export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "学习起始时间",
      "prop": "xxqssj",
      "span": 12
    },	  {
      "type": "input",
      "label": "学习终止时间",
      "prop": "xxzzsj",
      "span": 12
    },	  {
      "type": "input",
      "label": "培训班名称",
      "prop": "pxbmc",
      "span": 12
    },	  {
      "type": "input",
      "label": "培训学时",
      "prop": "pxxs",
      "span": 12
    },	  {
      "type": "input",
      "label": "培训类别",
      "prop": "pxlb",
      "span": 12
    },	  {
      "type": "input",
      "label": "主办单位",
      "prop": "zbdw",
      "span": 12
    },	  {
      "type": "input",
      "label": "参加出国出境",
      "prop": "cjcgcj",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否学历学位晋升",
      "prop": "sfxlxwjs",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
