export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id",
      "span": 12
    },	  {
      "type": "input",
      "label": "教职工id",
      "prop": "staffId",
      "span": 12
    },	  {
      "type": "input",
      "label": "异动类型",
      "prop": "changeType",
      "span": 12
    },	  {
      "type": "input",
      "label": "异动日期",
      "prop": "changeDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "异动开始日期",
      "prop": "changeStartDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "异动结束日期",
      "prop": "changeEndDate",
      "span": 12
    },	  {
      "type": "input",
      "label": "异动原因",
      "prop": "changeReason",
      "span": 12
    },	  {
      "type": "input",
      "label": "证明材料",
      "prop": "changeEvidence",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "memo",
      "span": 12
    },	  {
      "type": "input",
      "label": "删除标识",
      "prop": "delFlag",
      "span": 12
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "span": 12
    }  ]
}
