export const option = {
  align: 'center',
  border: true,
  index: true,
  indexLabel: '序号',
  searchMenuSpan: 4,
  addBtn: false,
  column: [{
      label: '编码',
      prop: 'bm',
      search: true,
    },
    {
      label: '适用岗位',
      prop: 'sygw',
      search: true,
      type: 'select',
      dicUrl: '/admin/dict/type/rygwlx_type',
      props: {
        "label": "label",
        "value": "value"
      },
    },
    {
      label: '描述',
      prop: 'ms',
    },
  ]
}
export const optionChild = {
  align: 'center',
  border: true,
  index: true,
  indexLabel: '序号',
  menuWidth: 140,
  labelWidth: 200,
  columnBtn: false,
  column: [{
      label: '应发工资',
      children: [{
          label: '国家工资',
          children: [{
              label: '项目名称',
              prop: 'gjgzxmsm'
            },
            {
              label: '说明',
              prop: 'gjgzsm'
            },
          ]
        },
        {
          label: '校内奖金',
          children: [{
              label: '项目名称',
              prop: 'xxnjjxmsm'
            },
            {
              label: '说明',
              prop: 'xxnjjsm'
            },
          ]
        },
        {
          label: '零星发放',
          children: [{
              label: '项目名称',
              prop: 'lxffxmsm'
            },
            {
              label: '说明',
              prop: 'lxffsm'
            },
          ]
        },
        {
          label: '不定时发放',
          prop: 'zjx',
          children: [{
              label: '项目名称',
              prop: 'bdsffxmsm'
            },
            {
              label: '说明',
              prop: 'bdsffsm'
            },
          ]
        },
      ]
    },
    {
      label: '应扣工资',
      children: [{
          label: '项目名称',
          prop: 'ykgzxmsm'
        },
        {
          label: '说明',
          prop: 'ykgzsm'
        },
      ]
    },
  ]
}

export const dataChilds = [
  [{
      gjgzxmsm: '岗位工资',
      gjgzsm: '',
      xxnjjxmsm: '校内岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '加班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '职业年金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '薪级工资',
      gjgzsm: '',
      xxnjjxmsm: '实训实验室津贴',
      xxnjjsm: '',
      lxffxmsm: '值班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '养老金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '上下班交通费补贴',
      gjgzsm: '',
      xxnjjxmsm: '技术津贴',
      xxnjjsm: '',
      lxffxmsm: '劳务费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '住房公积金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '独生子女父母奖励费',
      gjgzsm: '',
      xxnjjxmsm: '学科带头人津贴',
      xxnjjsm: '',
      lxffxmsm: '各种津贴费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '医疗保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '粮油补贴',
      gjgzsm: '',
      xxnjjxmsm: '组长津贴',
      xxnjjsm: '',
      lxffxmsm: '各种奖励费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '失业保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '护龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '租房补贴',
      xxnjjsm: '',
      lxffxmsm: '课题费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '个人所得税',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '政府特殊津贴',
      gjgzsm: '',
      xxnjjxmsm: '其他补贴',
      xxnjjsm: '',
      lxffxmsm: '高温费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '工会费',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '各类特殊岗位津贴',
      gjgzsm: '',
      xxnjjxmsm: '财政岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '节日费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '扣车贴',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派青年志愿人员赴云南扶贫补贴',
      gjgzsm: '',
      xxnjjxmsm: '各类特殊岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '一次性奖励',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '病假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派干部赴西藏等省市补贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '增发能级',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '事假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '其他',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '其他扣款',
      ykgzsm: '',
    },
  ],
  [{
      gjgzxmsm: '岗位工资',
      gjgzsm: '',
      xxnjjxmsm: '校内岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '加班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '职业年金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '薪级工资',
      gjgzsm: '',
      xxnjjxmsm: '组长津贴',
      xxnjjsm: '',
      lxffxmsm: '值班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '养老金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '上下班交通费补贴',
      gjgzsm: '',
      xxnjjxmsm: '学委津贴',
      xxnjjsm: '',
      lxffxmsm: '劳务费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '住房公积金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '独生子女父母奖励费',
      gjgzsm: '',
      xxnjjxmsm: '督导组津贴',
      xxnjjsm: '',
      lxffxmsm: '各种津贴费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '医疗保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '粮油补贴',
      gjgzsm: '',
      xxnjjxmsm: '行政兼课',
      xxnjjsm: '',
      lxffxmsm: '各种奖励费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '失业保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '教龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '租房补贴',
      xxnjjsm: '',
      lxffxmsm: '高温费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '个人所得税',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '护龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '其他补贴',
      xxnjjsm: '',
      lxffxmsm: '带教教师津贴',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '工会费',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '政府特殊津贴',
      gjgzsm: '',
      xxnjjxmsm: '工作室津贴',
      xxnjjsm: '',
      lxffxmsm: '节日费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '扣车贴',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '各类特殊岗位津贴',
      gjgzsm: '',
      xxnjjxmsm: '财政岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '一次性奖励',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '病假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派青年志愿人员赴云南扶贫补贴',
      gjgzsm: '',
      xxnjjxmsm: '各类特殊岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '增发能级',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '事假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派干部赴西藏等省市补贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '其他',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '其他扣款',
      ykgzsm: '',
    },
  ],
  [{
      gjgzxmsm: '岗位工资',
      gjgzsm: '',
      xxnjjxmsm: '校内岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '加班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '职业年金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '薪级工资',
      gjgzsm: '',
      xxnjjxmsm: '学科带头人津贴',
      xxnjjsm: '',
      lxffxmsm: '值班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '养老金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '上下班交通费补贴',
      gjgzsm: '',
      xxnjjxmsm: '骨干教师',
      xxnjjsm: '',
      lxffxmsm: '劳务费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '住房公积金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '独生子女父母奖励费',
      gjgzsm: '',
      xxnjjxmsm: '双师津贴',
      xxnjjsm: '',
      lxffxmsm: '各种津贴费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '医疗保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '粮油补贴',
      gjgzsm: '',
      xxnjjxmsm: '租房补贴',
      xxnjjsm: '',
      lxffxmsm: '各种奖励费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '失业保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '教龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '班主任津贴',
      xxnjjsm: '',
      lxffxmsm: '课题费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '个人所得税',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '护龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '班主任课时津贴',
      xxnjjsm: '',
      lxffxmsm: '高温费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '工会费',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '政府特殊津贴',
      gjgzsm: '',
      xxnjjxmsm: '其他补贴',
      xxnjjsm: '',
      lxffxmsm: '节日费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '扣车贴',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '各类特殊岗位津贴',
      gjgzsm: '',
      xxnjjxmsm: '其他补贴',
      xxnjjsm: '',
      lxffxmsm: '一次性奖励',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '病假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派青年志愿人员赴云南扶贫补贴',
      gjgzsm: '',
      xxnjjxmsm: '工作室津贴',
      xxnjjsm: '',
      lxffxmsm: '增发能级',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '事假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派干部赴西藏等省市补贴',
      gjgzsm: '',
      xxnjjxmsm: '各类特殊岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '其他',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '其他扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '特级教师津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '支教人员津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '',
      gjgzsm: '',
      xxnjjxmsm: '班主任课时津贴',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '',
      gjgzsm: '',
      xxnjjxmsm: '带教教师津贴',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '',
      gjgzsm: '',
      xxnjjxmsm: '各类特殊岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
  ],
  [{
      gjgzxmsm: '岗位工资',
      gjgzsm: '',
      xxnjjxmsm: '校内岗位津贴',
      xxnjjsm: '',
      lxffxmsm: '加班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '职业年金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '薪级工资',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '值班费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '养老金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '上下班交通费补贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '劳务费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '住房公积金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '独生子女父母奖励费',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '各种津贴费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '医疗保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '粮油补贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '各种奖励费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '失业保险金',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '教龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '课题费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '个人所得税',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '护龄津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '高温费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '工会费',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '政府特殊津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '节日费',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '扣车贴',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '各类特殊岗位津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '一次性奖励',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '病假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派青年志愿人员赴云南扶贫补贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '增发能级',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '事假扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '选派干部赴西藏等省市补贴',
      gjgzsm: '',
      xxnjjxmsm: '租房补贴',
      xxnjjsm: '',
      lxffxmsm: '其他',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '其他扣款',
      ykgzsm: '',
    },
    {
      gjgzxmsm: '特级教师津贴',
      gjgzsm: '',
      xxnjjxmsm: '',
      xxnjjsm: '',
      lxffxmsm: '',
      lxffsm: '',
      bdsffxmsm: '',
      bdsffsm: '',
      ykgzxmsm: '',
      ykgzsm: '',
    },
  ]
]
