export const option = {
  align: "center",
  border: true,
  columnBtn: false,
  menuWidth: 160,
  labelWidth: 100,
  column: [
    {
      label: "应发工资",
      display: false,
      children: [
        {
          label: "国家工资",
          display: false,
          children: [
            {
              type: "input",
              label: "项目名称",
              span: 24,
              display: true,
              prop: "gjgzXmmc",
              maxlength: 100,
              showWordLimit: false,
              required: true,
              labelTip: "国家工资 项目名称",
              tip: "国家工资 项目名称",
            },
            {
              type: "textarea",
              label: "项目描述",
              span: 24,
              display: true,
              prop: "gjgzXmms",
              maxlength: 200,
              showWordLimit: true,
              labelTip: "国家工资 项目描述",
              tip: "国家工资 项目描述",
            },
          ],
        },
        {
          label: "校内奖金",
          display: false,
          children: [
            {
              type: "input",
              label: "项目名称",
              span: 24,
              display: true,
              prop: "xnjjXmmc",
              maxlength: 100,
              showWordLimit: false,
              required: true,
              labelTip: "校内奖金 项目名称",
              tip: "校内奖金 项目名称",
            },
            {
              type: "textarea",
              label: "项目描述",
              span: 24,
              display: true,
              prop: "xnjjXmms",
              maxlength: 200,
              showWordLimit: true,
              labelTip: "校内奖金 项目描述",
              tip: "校内奖金 项目描述",
            },
          ],
        },
        {
          label: "零星发放",
          display: false,
          children: [
            {
              type: "input",
              label: "项目名称",
              span: 24,
              display: true,
              prop: "lxffXmmc",
              maxlength: 100,
              showWordLimit: false,
              required: true,
              labelTip: "零星发放 项目名称",
              tip: "零星发放 项目名称",
            },
            {
              type: "textarea",
              label: "项目描述",
              span: 24,
              display: true,
              prop: "lxffXmms",
              maxlength: 200,
              showWordLimit: true,
              labelTip: "零星发放 项目描述",
              tip: "零星发放 项目描述",
            },
          ],
        },
        {
          label: "不定时发放",
          display: false,
          children: [
            {
              type: "input",
              label: "项目名称",
              span: 24,
              display: true,
              prop: "bdsffXmmc",
              maxlength: 100,
              showWordLimit: false,
              required: true,
              labelTip: "不定时发放 项目名称",
              tip: "不定时发放 项目名称",
            },
            {
              type: "textarea",
              label: "项目描述",
              span: 24,
              display: true,
              prop: "bdsffXmms",
              maxlength: 200,
              showWordLimit: true,
              labelTip: "不定时发放 项目描述",
              tip: "不定时发放 项目描述",
            },
          ],
        },
      ],
    },
    {
      label: "应扣工资",
      display: false,
      children: [
        {
          type: "input",
          label: "项目名称",
          span: 24,
          display: true,
          prop: "ykgzXmmc",
          maxlength: 100,
          showWordLimit: false,
          required: true,
          labelTip: "应扣工资 项目名称",
          tip: "应扣工资 项目名称",
        },
        {
          type: "textarea",
          label: "项目描述",
          span: 24,
          display: true,
          prop: "ykgzXmms",
          maxlength: 200,
          showWordLimit: true,
          labelTip: "应扣工资 项目描述",
          tip: "应扣工资 项目描述",
        },
      ],
    },
  ],
};
