export const option = {
  labelWidth: 140,
  submitText: "保存",
  group: [
    {
      label: "参加校本研修总人数",
      column: [
        {
          type: "number",
          span: 24,
          display: true,
          prop: "cjxbyxzrs",
          controls: true,
          placeholder: "请输入参加校本研修总人数",
        },
      ],
    },
    {
      label: "职称情况",
      column: [
        {
          type: "number",
          label: "高级职称(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "gjzc",
        },
        {
          type: "number",
          label: "中级职称(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "zjzc",
        },
        {
          type: "number",
          label: "初级职称(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "cjzc",
        },
      ],
    },
    {
      label: "学历情况",
      column: [
        {
          type: "number",
          label: "博士研究生(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "bsyjs",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          controlsPosition: "right",
          required: true,
          rules: [
            {
              required: true,
              message: "博士研究生(人)必须填写",
            },
          ],
        },
        {
          type: "number",
          label: "硕士研究生(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "ssyjs",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          rules: [
            {
              required: true,
              message: "硕士研究生(人)必须填写",
            },
          ],
          required: true,
          controlsPosition: "right",
        },
        {
          type: "number",
          label: "本科学历(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "bkxl",
          rules: [
            {
              required: true,
              message: "本科学历(人)必须填写",
            },
          ],
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          required: true,
          controlsPosition: "right",
        },
        {
          type: "number",
          label: "专科学历(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "zkxl",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          rules: [
            {
              required: true,
              message: "专科学历(人)必须填写",
            },
          ],
          required: true,
          controlsPosition: "right",
        },
        {
          type: "number",
          label: "专科以下学历(人)",
          controls: true,
          span: 8,
          display: true,
          prop: "zkjyxxl",
          rules: [
            {
              required: true,
              message: "专科以下学历(人)必须填写",
            },
          ],
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          required: true,
        },
      ],
    },
    {
      label: "骨干情况",
      column: [
        {
          type: "number",
          label: "学科带头人(人)",
          span: 6,
          display: true,
          prop: "xkdtr",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          controls: true,
          controlsPosition: "right",
          required: true,
          rules: [
            {
              required: true,
              message: "学科带头人(人)必须填写",
            },
          ],
        },
        {
          type: "number",
          label: "区级骨干(人)",
          span: 6,
          display: true,
          prop: "qjgg",
          maxlength: 9999,
          showWordLimit: true,
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          controls: true,
          required: true,
          rules: [
            {
              required: true,
              message: "区级骨干(人)必须填写",
            },
          ],
          controlsPosition: "right",
        },
        {
          type: "number",
          label: "校级骨干(人)",
          span: 6,
          display: true,
          prop: "xjgg",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          controls: true,
          controlsPosition: "right",
          required: true,
          rules: [
            {
              required: true,
              message: "校级骨干(人)必须填写",
            },
          ],
        },
        {
          type: "number",
          label: "署级骨干(人)",
          span: 6,
          display: true,
          prop: "zjgg",
          minRows: 0,
          maxRows: 9999,
          step: 1,
          precision: 1,
          controls: true,
          controlsPosition: "right",
          required: true,
          rules: [
            {
              required: true,
              message: "署级骨干(人)必须填写",
            },
          ],
        },
      ],
    },
    {
      label: "现状分析",
      column: [
        {
          type: "textarea",
          placeholder: "请输入现状分析",
          span: 24,
          display: true,
          prop: "xzfx",
          maxlength: 200,
          showWordLimit: true,
          required: true,
          rules: [
            {
              required: true,
              message: "现状分析必须填写",
            },
          ],
        },
      ],
    },
    {
      label: "研修目标",
      column: [
        {
          type: "textarea",
          placeholder: "请输入研修目标",
          span: 24,
          display: true,
          prop: "yxmb",
          rules: [
            {
              required: true,
              message: "研修目标必须填写",
            },
          ],
          maxlength: 200,
          required: true,
          showWordLimit: true,
        },
      ],
    },
    {
      label: "研修任务",
      column: [
        {
          type: "textarea",
          placeholder: "研修任务",
          span: 24,
          display: true,
          prop: "yxrw",
          rules: [
            {
              required: true,
              message: "研修任务必须填写",
            },
          ],
          maxlength: 200,
          showWordLimit: true,
          required: true,
        },
      ],
    },
    {
      label: "保障措施",
      column: [
        {
          type: "textarea",
          placeholder: "保障措施",
          span: 24,
          display: true,
          prop: "bzcs",
          rules: [
            {
              required: true,
              message: "保障措施必须填写",
            },
          ],
          maxlength: 200,
          required: true,
          showWordLimit: true,
        },
      ],
    },
  ],
};
