export const option = {
  align: "center",
  border: true,
  dialogWidth: "80%",
  labelWidth: 150,
  searchSpan: 8,
  viewBtn: true,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  columnBtn: false,
  column: [
    {
      label: "学年",
      prop: "xn",
      type: "year",
      format: "yyyy",
      valueFormat: "yyyy",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      search: true,
    },
    {
      type: "select",
      label: "培训类型",
      dicData: [
        {
          label: "专业技能",
          value: 0,
        },
        {
          label: "理论知识",
          value: 1,
        },
        {
          label: "出国培训",
          value: 2,
        },
        {
          label: "学历学位教育",
          value: 3,
        },
        {
          label: "企业实践",
          value: 4,
        },
        {
          label: "其他",
          value: 5,
        },
      ],
      cascaderItem: [],
      span: 8,
      display: true,
      props: {
        label: "label",
        value: "value",
      },
      prop: "pxlx",
      clearable: true,
      required: true,
      rules: [
        {
          required: true,
          message: "请选择培训类型",
        },
      ],
    },
    {
      type: "input",
      label: "培训项目",
      span: 8,
      display: true,
      prop: "pxxm",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "培训项目必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "input",
      label: "培训机构",
      span: 8,
      display: true,
      prop: "pxjg",
      rules: [
        {
          required: true,
          message: "培训机构必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      hide: true,
    },
    {
      type: "select",
      label: "部门",
      span: 8,
      display: true,
      prop: "deptId",
      cascaderItem: [],
      props: {
        label: "name",
        value: "id",
        children: "children",
      },
      dicUrl: "/admin/dept/tree",
      dicMethod: "get",
      clearable: true,
      required: true,
      rules: [
        {
          required: true,
          message: "请选择系处",
        },
      ],
      dicFlag: true,
      disabled: true,
    },
    {
      type: "input",
      label: "姓名",
      span: 8,
      display: true,
      prop: "xm",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "姓名必须填写",
        },
      ],
      disabled: true,
      search: true,
    },
    {
      type: "input",
      label: "师训账号",
      span: 8,
      display: true,
      prop: "sxzh",
      rules: [
        {
          required: true,
          message: "师训账号必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      disabled: true,
    },
    {
      type: "daterange",
      label: "培训起止时间",
      span: 24,
      display: true,
      format: "yyyy-MM-dd",
      valueFormat: "yyyy-MM-dd",
      startPlaceholder: "培训开始日期",
      endPlaceholder: "培训结束日期",
      prop: "pxkssj",
      required: true,
      rules: [
        {
          required: true,
          message: "培训起止时间必须填写",
        },
      ],
    },
    {
      type: "input",
      label: "培训学时",
      span: 12,
      display: true,
      prop: "pxxs",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "培训学时必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "input",
      label: "折合次数",
      span: 12,
      display: true,
      prop: "zhcs",
      rules: [
        {
          required: true,
          message: "折合次数必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      hide: true,
    },
    {
      type: "textarea",
      label: "参训人员",
      span: 24,
      display: true,
      prop: "cxry",
      maxlength: 200,
      showWordLimit: true,
      required: true,
      rules: [
        {
          required: true,
          message: "参训人员必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "textarea",
      label: "备注",
      span: 24,
      display: true,
      prop: "bz",
      rules: [
        {
          required: true,
          message: "备注必须填写",
        },
      ],
      maxlength: 200,
      showWordLimit: true,
      required: true,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      type: "select",
      search: true,
    },
    {
      component: "elAlert",
      params: {
        title: "说明:",
        type: "warning",
        description:
          "每5个学时（半天）折合一次学习活动，每参与6次活动认定1学分；",
        closable: false,
        showIcon: true,
      },
      span: 24,
      hide: true,
    },
    {
      prop: "steps",
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: false,
    },
  ],
};
