export const option = {
  align: "center",
  border: true,
  dialogWidth: "80%",
  selection: true,
  columnBtn: false,
  viewBtn: true,
  searchSpan: 8,
  column: [
    {
      label: "学年",
      prop: "xn",
      type: "year",
      format: "yyyy",
      valueFormat: "yyyy",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      search: true,
    },
    {
      type: "select",
      label: "部门",
      span: 8,
      display: true,
      prop: "deptId",
      cascaderItem: [],
      props: {
        label: "name",
        value: "id",
        children: "children",
      },
      dicUrl: "/admin/dept/tree",
      dicMethod: "get",
      clearable: true,
      required: true,
      rules: [
        {
          required: true,
          message: "请选择系处",
        },
      ],
      dicFlag: true,
      disabled: true,
    },
    {
      type: "input",
      label: "姓名",
      span: 8,
      display: true,
      prop: "xm",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "姓名必须填写",
        },
      ],
      disabled: true,
      search: true,
    },
    {
      type: "input",
      label: "师训账号",
      span: 8,
      display: true,
      prop: "sxzh",
      rules: [
        {
          required: true,
          message: "师训账号必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      disabled: true,
    },
    {
      type: "dynamic",
      label: "子表单",
      span: 24,
      display: true,
      // selection: true,
      children: {
        align: "center",
        headerAlign: "center",
        index: false,
        addBtn: true,
        delBtn: true,
        column: [
          {
            type: "date",
            label: "时间",
            span: 24,
            display: true,
            format: "yyyy-MM-dd",
            valueFormat: "yyyy-MM-dd",
            prop: "sj",
            required: true,
            rules: [
              {
                required: true,
                message: "时间必须填写",
              },
            ],
          },
          {
            type: "input",
            label: "学校",
            span: 24,
            display: true,
            prop: "xx",
            maxlength: 30,
            required: true,
            rules: [
              {
                required: true,
                message: "学校必须填写",
              },
            ],
          },
          {
            type: "input",
            label: "班级",
            span: 24,
            display: true,
            prop: "bj",
            rules: [
              {
                required: true,
                message: "班级必须填写",
              },
            ],
            maxlength: 30,
            required: true,
          },
          {
            type: "input",
            label: "学科",
            span: 24,
            display: true,
            prop: "xk",
            rules: [
              {
                required: true,
                message: "学科必须填写",
              },
            ],
            maxlength: 30,
            required: true,
          },
          {
            type: "input",
            label: "课题",
            span: 24,
            display: true,
            prop: "kt",
            rules: [
              {
                required: true,
                message: "课题必须填写",
              },
            ],
            maxlength: 30,
            required: true,
          },
          {
            type: "input",
            label: "执教者",
            span: 24,
            display: true,
            prop: "zjz",
            rules: [
              {
                required: true,
                message: "执教者必须填写",
              },
            ],
            maxlength: 30,
            required: true,
          },
        ],
      },
      prop: "child",
    },
    {
      label: "状态",
      prop: "status",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      type: "select",
      search: true,
    },
    {
      component: "elAlert",
      params: {
        title: "说明:",
        type: "warning",
        description: "每参与6次活动认定1学分；",
        closable: false,
        showIcon: true,
      },
      span: 24,
      hide: true,
    },
    {
      prop: "steps",
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: false,
    },
  ],
};
