import { is_type } from "@/const/commonDict";

export const option = {
  align: "center",
  border: true,
  selection: true,
  searchSpan: 6,
  searchMenuSpan: 4,
  column: [
    {
      type: "input",
      label: "工号",
      span: 12,
      display: true,
      prop: "gh",
      maxlength: 30,
      required: true,
      rules: [{ required: true, message: "工号必须填写" }],
    },
    {
      type: "input",
      label: "师训账号",
      span: 12,
      display: true,
      prop: "sxzh",
      rules: [{ required: true, message: "师训账号必须填写" }],
      maxlength: 30,
      required: true,
    },
    {
      type: "input",
      label: "姓名",
      span: 12,
      display: true,
      prop: "xm",
      rules: [{ required: true, message: "姓名必须填写" }],
      maxlength: 30,
      required: true,
      search: true,
    },
    {
      type: "tree",
      label: "部门",
      span: 12,
      display: true,
      prop: "deptId",
      rules: [{ required: true, message: "请选择部门" }],
      cascaderItem: [],
      props: { label: "name", value: "id" },
      dataType: "number",
      dicMethod: "get",
      parent: true,
      dicUrl: "admin/dept/tree",
      required: true,
    },
    {
      type: "select",
      label: "职务",
      span: 12,
      display: true,
      prop: "zw",
      dicData: [
        { label: "选项一", value: 0 },
        { label: "选项二", value: 1 },
        { label: "选项三", value: 2 },
      ],
      cascaderItem: [],
      props: { label: "label", value: "value" },
      dataType: "string",
      required: true,
      rules: [{ required: true, message: "请选择职务" }],
      clearable: true,
    },
    {
      type: "input",
      label: "手机号",
      span: 12,
      display: true,
      prop: "lxdh",
      maxlength: 11,
      required: true,
      rules: [{ required: true, message: "手机号必须填写" }],
    },
    {
      type: "radio",
      label: "是否参加",
      span: 12,
      display: true,
      prop: "sfcj",
      rules: [{ required: true, message: "请选择单行文本" }],
      dicData: is_type,
      props: { label: "label", value: "value" },
      border: true,
      required: true,
      search: true,
    },
  ],
};
