export const option = {
  align: "center",
  border: true,
  dialogWidth: "80%",
  labelWidth: 150,
  searchSpan: 8,
  viewBtn: true,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  columnBtn: false,
  column: [
    {
      label: "学年",
      prop: "xn",
      type: "year",
      format: "yyyy",
      valueFormat: "yyyy",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      search: true,
    },
    {
      type: "select",
      label: "类别",
      span: 12,
      display: true,
      prop: "lb",
      dicData: [
        {
          label: "听学术讲座",
          value: 0,
        },
        {
          label: "参加署级及以上学术活动",
          value: 1,
        },
      ],
      props: {
        label: "label",
        value: "value",
      },
      required: true,
      rules: [
        {
          required: true,
          message: "请选择类别",
        },
      ],
    },
    {
      type: "input",
      label: "主题",
      span: 12,
      display: true,
      prop: "zt",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "主题必须填写",
        },
      ],
    },
    {
      type: "select",
      label: "部门",
      span: 8,
      display: true,
      prop: "deptId",
      cascaderItem: [],
      props: {
        label: "name",
        value: "id",
        children: "children",
      },
      dicUrl: "/admin/dept/tree",
      dicMethod: "get",
      clearable: true,
      required: true,
      rules: [
        {
          required: true,
          message: "请选择系处",
        },
      ],
      dicFlag: true,
      disabled: true,
    },
    {
      type: "input",
      label: "姓名",
      span: 8,
      display: true,
      prop: "xm",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "姓名必须填写",
        },
      ],
      disabled: true,
      search: true,
    },
    {
      type: "input",
      label: "师训账号",
      span: 8,
      display: true,
      prop: "sxzh",
      rules: [
        {
          required: true,
          message: "师训账号必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      disabled: true,
    },
    {
      type: "date",
      label: "时间",
      span: 6,
      display: true,
      format: "yyyy-MM-dd",
      valueFormat: "yyyy-MM-dd",
      prop: "sj",
      required: true,
      rules: [
        {
          required: true,
          message: "时间必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "input",
      label: "学时",
      span: 6,
      display: true,
      prop: "xs",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "学时必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "input",
      label: "地点",
      span: 6,
      display: true,
      prop: "dd",
      maxlength: 100,
      required: true,
      rules: [
        {
          required: true,
          message: "地点必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "number",
      label: "折合次数",
      span: 6,
      display: true,
      prop: "zhcs",
      rules: [
        {
          required: true,
          message: "折合次数必须填写",
        },
      ],
      minRows: 0,
      maxRows: 9999,
      step: 1,
      precision: 1,
      controls: true,
      controlsPosition: "right",
      required: true,
      hide: true,
    },
    {
      type: "input",
      label: "组织者",
      span: 12,
      display: true,
      prop: "zzz",
      maxlength: 30,
      required: true,
      rules: [
        {
          required: true,
          message: "组织者必须填写",
        },
      ],
      hide: true,
    },
    {
      type: "input",
      label: "主讲人",
      span: 12,
      display: true,
      prop: "zjr",
      rules: [
        {
          required: true,
          message: "主讲人必须填写",
        },
      ],
      maxlength: 30,
      required: true,
      hide: true,
    },
    {
      type: "textarea",
      label: "主要内容记录",
      span: 24,
      display: true,
      prop: "zynrjr",
      maxlength: 10000,
      showWordLimit: true,
      hide: true,
    },
    {
      type: "textarea",
      label: "个人学习收获与体会",
      span: 24,
      display: true,
      prop: "grxxshyth",
      maxlength: 10000,
      showWordLimit: true,
      required: false,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      type: "select",
      search: true,
    },
    {
      component: "elAlert",
      params: {
        title: "说明:",
        type: "warning",
        description: `1．根据个人学习情况在“类别”中选择相应栏目，并在（）中打“√”；
                      2．每5个学时（半天）折合一次学习活动，每参与6次活动认定1学分；`,
        closable: false,
        showIcon: true,
      },
      span: 24,
      hide: true,
    },
    {
      prop: "steps",
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: false,
    },
  ],
};
